--- #YAML:1.0
name:         Parallel-Forker
version:      1.246
version_from: lib/Parallel/Forker.pm
abstract:     Parallel job forking and management, with expression based control
installdirs:  site
license:      perl
author:
    - Wilson Snyder <wsnyder@wsnyder.org>
resources:
    homepage: http://www.veripool.org
requires:
    Proc::ProcessTable:            0.4
    Scalar::Util:		   0
    Test::More:                    0
    Time::HiRes:                   0

meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.4.html
    version: 1.4
distribution_type: module
generated_by: hand
